apiVersion: 1

datasources:
  - name: icinga2-influxDB
    type: influxdb
    access: server
    database: ${INFLUXDB_V1_DATABASE}
    user: ${INFLUXDB_V1_USER}
    url: http://influxdb:8086
    jsonData:
      httpMode: GET
    secureJsonData:
      password: ${INFLUXDB_V1_PASSWORD}
  - name: influxdb-flux
    type: influxdb
    access: server
    url: http://influxdb:8086
    secureJsonData:
      token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    jsonData:
      version: Flux
      organization: ${DOCKER_INFLUXDB_INIT_ORG}
      defaultBucket: ${DOCKER_INFLUXDB_INIT_BUCKET}
      tlsSkipVerify: true

